openapi: 3.0.0
info:
  version: 1.0.0
  title: Revizor Analysis Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    CheckingCombination:
      type: object
      required:
        - projects_ids
        - rules_ids
      properties:
        name:
          type: string
          nullable: true
        projects_ids:
          type: array
          items:
            type: string
        rules_ids:
          type: array
          items:
            type: string
paths:
  /check:
    post:
      summary: Start a check of the projects given
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckingCombination'
      responses:
        '202':
          description: successful operation
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error