openapi: 3.0.0
info:
  version: 1.0.0
  title: Revizor Rules Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    CheckingCombination:
      type: object
      required:
        - id
        - projects_ids
        - rules_ids
      properties:
        id:
          type: integer
        name:
          type: string
          nullable: true
        projects_ids:
          type: array
          items:
            type: integer
        rules_ids:
          type: array
          items:
            type: integer
    ReportData:
      type: object
      properties:
        reportData:
          type: array
          items:
            type: object
            properties:
              project_id:
                type: integer
              rules_matching:
                type: array
                items:
                  type: object
                  properties:
                    ruleId:
                      type: integer
                    isApplied:
                      type: boolean
paths:
  /report:
    post:
      summary: Create a report
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - checkingCombination
                - reportId
              properties:
                checkingCombination:
                  $ref: '#/components/schemas/CheckingCombination'
                reportId:
                  type: integer
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '409':
          description: report's id is used
        '500':
          description: internal error
    put:
      summary: Update a report
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - reportId
              properties:
                reportId:
                  type: integer
      responses:
        '200':
          description: updated successfully
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /report/{reportId}:
    get:
      summary: Get a report with it's results
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReportData'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    delete:
      summary: Delete a report
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: deleted successfully
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error–µ
