openapi: 3.0.0
info:
  version: 1.0.0
  title: Revizor Rules Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    CreateReportDto:
      type: object
      properties:
        groupId:
          type: string
        reportId:
          type: string
      required:
        - groupId
        - reportId
    GetReportDto:
      type: object
      properties:
        date:
          type: string
        groupId:
          type: string
        results:
          type: array
          items:
            type: object
            properties:
              location:
                type: string
              violatedRuleId:
                type: string
      required:
        - groupId
        - date
        - results
paths:
  /report:
    post:
      summary: Create a report
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReportDto'
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '409':
          description: report's id is used
        '500':
          description: internal error
    put:
      summary: Update a report
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReportDto'
      responses:
        '200':
          description: updated successfully
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /report/{reportId}:
    get:
      summary: Get a report with it's results
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReportDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    delete:
      summary: Delete a report
      parameters:
        - name: reportId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: deleted successfully
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error–µ