openapi: 3.1.0
info:
  version: 1.0.0
  title: Revizor Rules Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    CreateRuleDto:
      type: object
      properties:
        templateId:
          type: string
        projectId:
          type: string
        fileName:
          type: string
        lineId:
          type: number
      required:
        - templateId
        - projectId
        - fileName
paths:
  /rule:
    get:
      summary: Get rule for a project
      parameters:
        - name: projectId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRuleDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    put:
      summary: Create a rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRuleDto'
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /rule/{ruleId}:
    delete:
      summary: Remove a rule from a project
      parameters:
        - name: projectId
          in: query
          required: true
          schema:
            type: string
        - name: ruleId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error