openapi: 3.1.0
info:
  version: 1.0.0
  title: Revizor Rules Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    GetRuleDto:
      type: object
      properties:
        id:
          type: string
          description: uuid
        typeId:
          type: string
        params:
          type: string
          description: json obj. Necessarily field - applyToURI
      required:
        - typeId
        - applyToURI
        - value
    CreateRuleDto:
      type: object
      properties:
        id:
          type: string
          description: uuid
        typeId:
          type: string
        params:
          type: string
          description: json obj. Necessarily field - applyToURI
      required:
        - typeId
        - applyToURI
        - value
    GetPolicyDto:
      type: object
      properties:
        id:
          type: string
          description: uuid
        projectId:
          type: string
        rulesIds:
          type: array
          items:
            type: string
      required:
        - projectId
        - rulesIds
    CreatePolicyDto:
      type: object
      properties:
        projectId:
          type: string
          description: uuid
        rulesIds:
          type: array
          items:
            type: string
      required:
        - projectId
        - rulesIds
paths:
  /rule:
    post:
      summary: Create a rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRuleDto'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRuleDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /rule/{id}:
    get:
      summary: Get rule for a project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRuleDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    delete:
      summary: Remove a rule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRuleDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /policy:
    post:
      summary: Create a rules application policy
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePolicyDto'
      responses:
        '201':
          description: created
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /policy/{id}:
    get:
      summary: Retrieve a rules application policy
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPolicyDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    delete:
      summary: Remove a policy from a project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPolicyDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
