openapi: 3.1.0
info:
  version: 1.0.0
  title: Revizor Rules Service API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
components:
  schemas:
    GetRuleDto:
      type: object
      properties:
        id:
          type: string
        templateId:
          type: string
        applyToURI:
          description: May be a link to a file. The <<lineId>> and <<symbolId>> optional query params may be specified to point to specific location in a resouce.
          type: string
        value:
          type: string
      required:
        - templateId
        - applyToURI
        - value
    CreateRuleDto:
      type: object
      properties:
        id:
          type: string
        templateId:
          type: string
        applyToURI:
          description: May be a link to a file. The <<lineId>> and <<symbolId>> optional query params may be specified to point to specific location in a resouce.
          type: string
        value:
          type: string
      required:
        - templateId
        - applyToURI
        - value
paths:
  /rule:
    post:
      summary: Create a rule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRuleDto'
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
  /rule/{id}:
    get:
      summary: Get rule for a project
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRuleDto'
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error
    delete:
      summary: Remove a rule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '401':
          description: unauthorized
        '403':
          description: forbidden
        '500':
          description: internal error